### PR TITLE
Different Applicative and Monoid instance for Matrix

### PR DESCRIPTION
**Pull request by davidsd**
The instances for `Applicative` and `Monoid` from `Data.Matrix` involve size-changing operations that are incompatible with static sizing. These alternative implementations have different behavior from those in `Data.Matrix`, but they are compatible with the types of `Applicative` and `Monoid`.

### CODE REVIEW

**Comment by wchresta** [comment]
Very cool! Thanks very much for this!

**Comment by wchresta** [comment]
This should resolve #2

**Comment by wchresta** [comment]
@davidsd Looks good, I reran the tests and the run through now. Also adding some additional tests.

I have thought a bit about the right choice for `pure`. I tend to want to use a diagonal matrix here instead of the constant-everywhere matrix but I realize this is wonky when it comes to non-diagonal matrices.
Thoughts on if the constant matrix a natural choice here?

**Comment by davidsd** [comment]
Hi Wanja,

The constant-everywhere matrix is the only choice that doesn't require a
Num instance for the elements. People may want to use Matrices in cases
where the entries do not have a Num instance (I have some examples in my
code). In that case, it is nice to still be able to use Applicative
combinators. I also suspect that the constant-everywhere matrix is the only
choice that satisfies the Applicative laws, for example

pure f <*> pure a = pure (f a)

does not work if pure creates a diagonal matrix, since firstly if f is a
function, it does not have a Num instance, and secondly even if we did
somehow define pure f as a diagonal matrix with f's on the diagonal, there
is no way to compose the off-diagonal elements above.

Finally, the diagonal matrix is less natural for non-square matrices.

For these reasons, I think constant-everywhere is the only
reasonable/natural choice.

Best,
David

**Comment by wchresta** [comment]
Yup, I didn't realize we didn't have a 0 without Monoid. Alright, thanks for the elaboration :)

**Pull request merged**
